kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloudflare-dyndns
  labels:
    app: cloudflare-dyndns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-dyndns
  template:
    metadata:
      labels:
        app: cloudflare-dyndns
    spec:
      containers:
      - image: stevemcquaid/cloudflare-dyndns-amd64:latest
        imagePullPolicy: Always
        name: cloudflare-dyndns
        args:
          - "/run"
          - "--config"
          - "/config/config.env"
        #env:
          #- name: DOMAIN
            #value: rbaz.com
          #- name: SUBDOMAIN
            #value: ip 
        volumeMounts:
        - name: cloudflare-dyndns
          mountPath: "/config/"
          readOnly: true
      volumes:
      - name: cloudflare-dyndns
        secret:
          secretName: cloudflare-dyndns
